[package]
name = "cfy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cfy"
path = "src/main.rs"

[dependencies]
cfy-core.workspace = true
clap.workspace = true
clap_complete.workspace = true
tokio.workspace = true
