[package]
name = "cfy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cfy"
path = "src/main.rs"

[dependencies]
cfy-api.workspace = true
cfy-auth.workspace = true
cfy-config.workspace = true
cfy-docs.workspace = true
cfy-hydrogen.workspace = true
cfy-organization.workspace = true
cfy-core.workspace = true
cfy-process.workspace = true
cfy-store.workspace = true
clap.workspace = true
clap_complete.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
