[package]
name = "cfy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cfy"
path = "src/main.rs"

[[bin]]
name = "catify"
path = "src/bin/catify.rs"

[dependencies]
cfy-api.workspace = true
cfy-app.workspace = true
cfy-auth.workspace = true
cfy-build.workspace = true
cfy-bulk.workspace = true
cfy-config.workspace = true
cfy-deploy.workspace = true
cfy-docs.workspace = true
cfy-dev.workspace = true
cfy-extension-adapter.workspace = true
cfy-functions.workspace = true
cfy-hydrogen.workspace = true
cfy-organization.workspace = true
cfy-core.workspace = true
cfy-plugins.workspace = true
cfy-process.workspace = true
cfy-store.workspace = true
cfy-tunnel.workspace = true
cfy-theme-init.workspace = true
cfy-upgrade.workspace = true
clap.workspace = true
clap_complete.workspace = true
crossterm.workspace = true
brotli.workspace = true
notify.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tar.workspace = true
zip = "2"
tokio.workspace = true
url.workspace = true
