[package]
name = "cfy-hydrogen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cfy-core.workspace = true
cfy-config.workspace = true
cfy-process.workspace = true
regex = "1.13"
reqwest.workspace = true
rustls.workspace = true
serde_json.workspace = true
sha2.workspace = true
swc_common = "26.0.0"
swc_ecma_codegen = "32.0.0"
swc_ecma_parser = "45.1.1"
swc_ecma_transforms_base = "49.0.1"
swc_ecma_transforms_typescript = "55.0.2"
thiserror.workspace = true
tokio.workspace = true
zip.workspace = true
