[package]
name = "cfy-theme-init"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cfy-core.workspace = true
cfy-process.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.21.0"
tokio.workspace = true
